hostname = ma75.update.netease.com

^https:\/\/ma75\.update\.netease\.com\/config\/.*\.json url script-request-header https://raw.githubusercontent.com/A-Kevin1217/resources/refs/heads/master/resources/js/netease_remove_cache.js