hostname = beta.radiance.thatgamecompany.com

^https:\/\/beta\.radiance\.thatgamecompany\.com\/account\/get_event_schedule url script-response-body https://raw.githubusercontent.com/A-Kevin1217/resources/refs/heads/master/resources/js/skybeta.js