hostname = ma75.update.netease.com

^https:\/\/ma75\.update\.netease\.com\/config\/.*\.json url script-response-body https://raw.githubusercontent.com/A-Kevin1217/resources/refs/heads/master/resources/js/netease_game.js